language: java
script:
    - javac -cp "./libs/*:." -encoding utf-8 MyHttpServer.java ExchangeUtils.java LoginHandler.java
  - javac -cp "./libs/*:." -encoding utf-8 Server.java 
  - java -cp "./libs/:." -server -Xms800m -Xmx800m -Xmn500m -Dfile.encoding=utf-8 Server
